services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5173:5173"

  backend:
    image: backend
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "3000:3000"
